name: 'Project Compliance Check'
description: 'Runs BHoM project compliance checks on changed .csproj files'
author: 'BHoM Test Toolkit'

inputs:
  files:
    description: 'Space-separated list of .csproj files to check (if not provided, will check all changed .csproj files)'
    required: false
    default: ''
  github-token:
    description: 'GitHub token for accessing repository'
    required: false
    default: ${{ github.token }}
  fail-on-error:
    description: 'Whether to fail the action if compliance errors are found'
    required: false
    default: 'true'
  assembly-description:
    description: 'Expected assembly description URL for organization validation'
    required: false
    default: ''

outputs:
  results:
    description: 'JSON string containing compliance check results'
  has-errors:
    description: 'Whether any compliance errors were found'
  error-count:
    description: 'Number of compliance errors found'

runs:
  using: 'docker'
  image: '../shared/Dockerfile'
  env:
    CHECK_TYPE: 'project'
    INPUT_FILES: ${{ inputs.files }}
    GITHUB_TOKEN: ${{ inputs.github-token }}
    FAIL_ON_ERROR: ${{ inputs.fail-on-error }}
    ASSEMBLY_DESCRIPTION: ${{ inputs.assembly-description }}

branding:
  icon: 'settings'
  color: 'orange'
